### ISSUE TITLE
Discourse upgrade page broken

### ISSUE THREAD

**Issue by terraboss** [kasperpeulen/discourse-mathjax#17]
Hi,
it turns out, that my http://domain.tld/admin/upgrade page is broken after installing your plugin. If I'm going to remove this and rebuild my docker based Discourse, everything seems to be working fine.  

My (latest) version is: 1.2.0.beta8

Any clue? Thank you all in advance.

**Comment by lidel** [comment]
@terraboss what you mean by 'broken'?
I am using discourse-mathjax plugin with Discourse 1.2.0.beta8 and  `/admin/upgrade` loads just fine.  
Related section of my `/var/discourse/containers/app.yml` looks like this:

```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/kasperpeulen/discourse-mathjax
```
